name: Android Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/expo-setup
    - uses: ./.github/actions/android-setup
    - name: Build Android Release
      run: |
        npm run android-release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.aab
        path: android/app/build/outputs/bundle/release/
